project:
  type: website

website:
  title: "Reports Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - hello.qmd
      - about.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



